<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="3" time="0.055" timestamp="2025-03-31T02:46:24.248534-03:00" hostname="ubuntu24-B550M-AORUS-ELITE"><testcase classname="tests.models.test_caminhos" name="test_validador_caminho_vazio" time="0.002" /><testcase classname="tests.models.test_caminhos" name="test_validador_caminho_apenas_espacos" time="0.001" /><testcase time="0.000" /><testcase classname="pytest" name="internal" time="0.000"><error message="internal error">Traceback (most recent call last):
  File "/home/pedro-pm-dias/API_LOCAL/GitHub/UniBMark/.venv/lib/python3.12/site-packages/_pytest/main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro-pm-dias/API_LOCAL/GitHub/UniBMark/.venv/lib/python3.12/site-packages/_pytest/main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/home/pedro-pm-dias/API_LOCAL/GitHub/UniBMark/.venv/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro-pm-dias/API_LOCAL/GitHub/UniBMark/.venv/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro-pm-dias/API_LOCAL/GitHub/UniBMark/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 156, in _multicall
    teardown[0].send(outcome)
  File "/home/pedro-pm-dias/API_LOCAL/GitHub/UniBMark/.venv/lib/python3.12/site-packages/pytest_cov/plugin.py", line 329, in pytest_runtestloop
    self.cov_controller.finish()
  File "/home/pedro-pm-dias/API_LOCAL/GitHub/UniBMark/.venv/lib/python3.12/site-packages/pytest_cov/engine.py", line 47, in ensure_topdir_wrapper
    original_cwd = Path.cwd()
                   ^^^^^^^^^^
  File "/usr/lib/python3.12/pathlib.py", line 1197, in cwd
    return cls().absolute()
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/pathlib.py", line 1225, in absolute
    result = self.with_segments(cwd)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/pathlib.py", line 385, in with_segments
    return type(self)(*pathsegments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/pathlib.py", line 1436, in __new__
    raise NotImplementedError(
NotImplementedError: cannot instantiate 'WindowsPath' on your system</error></testcase></testsuite></testsuites>